export type PullRequest = {
  id: string;
  title: string;
  body: string | null;
  url: string;
  htmlUrl: string;
  diffUrl: string;
  patchUrl: string;
  issueUrl: string;
  commitsUrl: string;
  reviewCommentsUrl: string;
  commentsUrl: string;
  statusesUrl: string;
  isMerged: boolean;
  isMergeable: boolean;
  isRebaseable: boolean;
  number: number;
  state: string;
  commits: number;
  additions: number;
  deletions: number;
  changedFiles: number;
  isDraft: boolean;
  githubId: string;
  repositoryId: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'MERGED';
  mergedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};
